#  Site wide configuration

title: "NATO Architecture Framework v. 4"
description: ""
locale: en_UK

baseurl: "/naf4-publication"

# Jekyll configuration

defaults:
  - scope:
      path: "naf/introduction"
    values:
      layout: "specification"
      rasterimages: "http://stavnstrup.github.io/naf4-raster/introduction/"
      svgimages: "/images/introduction/"
  - scope:
      path: "naf/methodology"
    values:
      layout: "specification"
      rasterimages: "http://stavnstrup.github.io/naf4-raster/methodology/"
      svgimages: "/images/methodology/"

#sass:
#  style: compressed

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - .editorconfig
  - .asset-cache
  - .sass-cache
  - Vagrantfile
  - Gemfile.lock
  - .vagrant
  - packages.json
  - gulpfile.js
  - node_modules
  - _sass/styles.scss

# Collection
