#  Site wide configuration

title: "NATO Architecture Framework v. 4"
description: ""
locale: en_UK

# Jekyll configuration

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - .editorconfig
  - .asset-cache
  - .sass-cache
  - Vagrantfile
  - Gemfile
  - Gemfile.lock

# Collection
