#  Site wide configuration

title: "NATO Architecture Framework v. 4"
description: ""
locale: en_UK

baseurl: "/naf4-publication"

# Jekyll configuration

defaults:
  - scope:
      path: "naf/"
    values:
      layout: "specification"
  - scope:
      path: "naf/introduction"
    values:
      docid: "intro"
      fullpath: "/naf/introduction/"
      layout: "specification"
      rasterimages: "http://stavnstrup.github.io/naf4-raster/introduction/"
      svgimages: "/images/introduction/"
  - scope:
      path: "naf/methodology"
    values:
      docid: "meth"
      fullpath: "/naf/methodology/"
      layout: "specification"
      rasterimages: "http://stavnstrup.github.io/naf4-raster/methodology/"
      svgimages: "/images/methodology/"
  - scope:
      path: "naf/metamodel"
    values:
      docid: "meta"
      fullpath: "/naf/metamodel/"
      layout: "specification"
      rasterimages: "http://stavnstrup.github.io/naf4-raster/meta-model/"
      svgimages: "/images/metamodel/"
  - scope:
      path: "naf/examples"
    values:
      docid: "exam"
      fullpath: "/naf/examples/"
      layout: "specification"
      rasterimages: "http://stavnstrup.github.io/naf4-raster/examples/"
      svgimages: "/images/examples/"

#sass:
#  style: compressed

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - .editorconfig
  - .asset-cache
  - .sass-cache
  - Vagrantfile
  - Gemfile.lock
  - .vagrant
  - packages.json
  - gulpfile.js
  - node_modules
  - _sass/styles.scss

# Collection
